/** BullaFrendLendV2 ABI — declared `as const` for viem type inference. */
export const bullaFrendLendV2Abi = [
    {
        inputs: [
            {
                components: [
                    { internalType: 'uint256', name: 'termLength', type: 'uint256' },
                    {
                        components: [
                            { internalType: 'uint16', name: 'interestRateBps', type: 'uint16' },
                            { internalType: 'uint16', name: 'numberOfPeriodsPerYear', type: 'uint16' },
                        ],
                        internalType: 'struct InterestConfig',
                        name: 'interestConfig',
                        type: 'tuple',
                    },
                    { internalType: 'uint256', name: 'loanAmount', type: 'uint256' },
                    { internalType: 'address', name: 'creditor', type: 'address' },
                    { internalType: 'address', name: 'debtor', type: 'address' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'address', name: 'token', type: 'address' },
                    { internalType: 'uint256', name: 'impairmentGracePeriod', type: 'uint256' },
                    { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
                    { internalType: 'address', name: 'callbackContract', type: 'address' },
                    { internalType: 'bytes4', name: 'callbackSelector', type: 'bytes4' },
                ],
                internalType: 'struct LoanRequestParams',
                name: 'offer',
                type: 'tuple',
            },
        ],
        name: 'offerLoan',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            {
                components: [
                    { internalType: 'uint256', name: 'termLength', type: 'uint256' },
                    {
                        components: [
                            { internalType: 'uint16', name: 'interestRateBps', type: 'uint16' },
                            { internalType: 'uint16', name: 'numberOfPeriodsPerYear', type: 'uint16' },
                        ],
                        internalType: 'struct InterestConfig',
                        name: 'interestConfig',
                        type: 'tuple',
                    },
                    { internalType: 'uint256', name: 'loanAmount', type: 'uint256' },
                    { internalType: 'address', name: 'creditor', type: 'address' },
                    { internalType: 'address', name: 'debtor', type: 'address' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'address', name: 'token', type: 'address' },
                    { internalType: 'uint256', name: 'impairmentGracePeriod', type: 'uint256' },
                    { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
                    { internalType: 'address', name: 'callbackContract', type: 'address' },
                    { internalType: 'bytes4', name: 'callbackSelector', type: 'bytes4' },
                ],
                internalType: 'struct LoanRequestParams',
                name: 'offer',
                type: 'tuple',
            },
            {
                components: [
                    { internalType: 'string', name: 'tokenURI', type: 'string' },
                    { internalType: 'string', name: 'attachmentURI', type: 'string' },
                ],
                internalType: 'struct ClaimMetadata',
                name: 'metadata',
                type: 'tuple',
            },
        ],
        name: 'offerLoanWithMetadata',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'offerId', type: 'uint256' }],
        name: 'rejectLoanOffer',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'offerId', type: 'uint256' }],
        name: 'acceptLoan',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'offerId', type: 'uint256' },
            { internalType: 'address', name: 'receiver', type: 'address' },
        ],
        name: 'acceptLoanWithReceiver',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'claimId', type: 'uint256' },
            { internalType: 'uint256', name: 'paymentAmount', type: 'uint256' },
        ],
        name: 'payLoan',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'claimId', type: 'uint256' }],
        name: 'impairLoan',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'claimId', type: 'uint256' }],
        name: 'markLoanAsPaid',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: 'loanId', type: 'uint256' },
            { internalType: 'address', name: 'callbackContract', type: 'address' },
            { internalType: 'bytes4', name: 'callbackSelector', type: 'bytes4' },
        ],
        name: 'setPaidLoanCallback',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'claimId', type: 'uint256' }],
        name: 'getLoan',
        outputs: [
            {
                components: [
                    { internalType: 'uint256', name: 'claimAmount', type: 'uint256' },
                    { internalType: 'uint256', name: 'paidAmount', type: 'uint256' },
                    { internalType: 'enum Status', name: 'status', type: 'uint8' },
                    { internalType: 'enum ClaimBinding', name: 'binding', type: 'uint8' },
                    { internalType: 'address', name: 'debtor', type: 'address' },
                    { internalType: 'address', name: 'creditor', type: 'address' },
                    { internalType: 'address', name: 'token', type: 'address' },
                    { internalType: 'address', name: 'controller', type: 'address' },
                    { internalType: 'uint256', name: 'dueBy', type: 'uint256' },
                    { internalType: 'uint256', name: 'acceptedAt', type: 'uint256' },
                    {
                        components: [
                            { internalType: 'uint16', name: 'interestRateBps', type: 'uint16' },
                            { internalType: 'uint16', name: 'numberOfPeriodsPerYear', type: 'uint16' },
                        ],
                        internalType: 'struct InterestConfig',
                        name: 'interestConfig',
                        type: 'tuple',
                    },
                    {
                        components: [
                            { internalType: 'uint256', name: 'accruedInterest', type: 'uint256' },
                            { internalType: 'uint256', name: 'latestPeriodNumber', type: 'uint256' },
                            { internalType: 'uint16', name: 'protocolFeeBps', type: 'uint16' },
                            { internalType: 'uint256', name: 'totalGrossInterestPaid', type: 'uint256' },
                        ],
                        internalType: 'struct InterestComputationState',
                        name: 'interestComputationState',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct Loan',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'claimId', type: 'uint256' }],
        name: 'getTotalAmountDue',
        outputs: [
            { internalType: 'uint256', name: 'remainingPrincipal', type: 'uint256' },
            { internalType: 'uint256', name: 'grossInterest', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: 'offerId', type: 'uint256' }],
        name: 'getLoanOffer',
        outputs: [
            {
                components: [
                    {
                        components: [
                            { internalType: 'uint256', name: 'termLength', type: 'uint256' },
                            {
                                components: [
                                    { internalType: 'uint16', name: 'interestRateBps', type: 'uint16' },
                                    { internalType: 'uint16', name: 'numberOfPeriodsPerYear', type: 'uint16' },
                                ],
                                internalType: 'struct InterestConfig',
                                name: 'interestConfig',
                                type: 'tuple',
                            },
                            { internalType: 'uint256', name: 'loanAmount', type: 'uint256' },
                            { internalType: 'address', name: 'creditor', type: 'address' },
                            { internalType: 'address', name: 'debtor', type: 'address' },
                            { internalType: 'string', name: 'description', type: 'string' },
                            { internalType: 'address', name: 'token', type: 'address' },
                            { internalType: 'uint256', name: 'impairmentGracePeriod', type: 'uint256' },
                            { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
                            { internalType: 'address', name: 'callbackContract', type: 'address' },
                            { internalType: 'bytes4', name: 'callbackSelector', type: 'bytes4' },
                        ],
                        internalType: 'struct LoanRequestParams',
                        name: 'params',
                        type: 'tuple',
                    },
                    { internalType: 'bool', name: 'requestedByCreditor', type: 'bool' },
                ],
                internalType: 'struct LoanOffer',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const;
