/**
 * sync-registry.ts
 *
 * Fetches registry.json from the bulla-registry GitHub repo and generates a typed
 * TypeScript module at src/generated/registry.ts. The generated file is committed to the repo.
 *
 * Factoring pool addresses are read from the "factoring-contracts" group within registry.json.
 *
 * Usage:
 *   yarn sync-registry
 *
 * Source:
 *   https://github.com/bulla-network/bulla-registry/blob/main/registry.json
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SUPPORTED_CHAIN_IDS } from '../src/domain/types/eth.js';

const REGISTRY_URL = 'https://raw.githubusercontent.com/bulla-network/bulla-registry/main/registry.json';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

interface RegistryNetwork {
    name: string;
    chainId: number;
    graphql: string;
    contracts: Record<string, Record<string, string>>;
}

interface Registry {
    generatedAt: string;
    networks: Record<string, RegistryNetwork>;
}

/** Parse pool name from key like "bullaFactoringV2_1_TCS" → "TCS", "bullaFactoringV1_TARAM" → "TARAM" */
function parsePoolName(key: string): string {
    const parts = key.split('_');
    return parts[parts.length - 1]!;
}

async function main() {
    console.log(`Fetching registry from: ${REGISTRY_URL}`);
    const response = await fetch(REGISTRY_URL);
    if (!response.ok) {
        throw new Error(`Failed to fetch registry: ${response.status} ${response.statusText}`);
    }
    const registry: Registry = (await response.json()) as Registry;

    const contracts: string[] = [];
    const subgraphs: string[] = [];
    const chainNames: string[] = [];
    const factoringPools: string[] = [];

    for (const chainIdStr of Object.keys(registry.networks)) {
        const chainId = Number(chainIdStr);
        if (!(SUPPORTED_CHAIN_IDS as readonly number[]).includes(chainId)) continue;

        const network = registry.networks[chainIdStr]!;

        // Extract bullaInstantPayment address from bulla-contracts group
        const bullaContracts = network.contracts['bulla-contracts'];
        const instantPaymentAddr = bullaContracts?.['bullaInstantPayment'];

        // Extract bullaInvoice and frendLendV2 addresses from bulla-contracts-v2 group
        const bullaContractsV2 = network.contracts['bulla-contracts-v2'];
        const invoiceAddr = bullaContractsV2?.['bullaInvoice'];
        const frendLendV2Addr = bullaContractsV2?.['frendLendV2'];
        const approvalRegistryAddr = bullaContractsV2?.['bullaApprovalRegistry'];
        const claimV2Addr = bullaContractsV2?.['bullaClaimV2'];

        if (!instantPaymentAddr) {
            console.warn(`  Warning: Missing bullaInstantPayment for chain ${chainId} (${network.name}), skipping`);
            continue;
        }

        const invoicePart = invoiceAddr ? `, bullaInvoice: '${invoiceAddr}' as EthAddress` : '';
        const frendLendV2Part = frendLendV2Addr ? `, frendLendV2: '${frendLendV2Addr}' as EthAddress` : '';
        const approvalRegistryPart = approvalRegistryAddr ? `, bullaApprovalRegistry: '${approvalRegistryAddr}' as EthAddress` : '';
        const claimV2Part = claimV2Addr ? `, bullaClaimV2: '${claimV2Addr}' as EthAddress` : '';
        contracts.push(`    ${chainId}: { bullaInstantPayment: '${instantPaymentAddr}' as EthAddress${invoicePart}${frendLendV2Part}${approvalRegistryPart}${claimV2Part} },`);
        subgraphs.push(`    ${chainId}: '${network.graphql}',`);
        chainNames.push(`    ${chainId}: '${network.name}',`);

        // Extract factoring pool addresses from factoring-contracts group
        const factoringContracts = network.contracts['factoring-contracts'];
        if (factoringContracts) {
            const poolEntries: string[] = [];
            for (const [key, address] of Object.entries(factoringContracts)) {
                const name = parsePoolName(key);
                poolEntries.push(`{ name: '${name}', address: '${address}' as EthAddress }`);
            }
            if (poolEntries.length > 0) {
                factoringPools.push(`    ${chainId}: [${poolEntries.join(', ')}],`);
            }
        }
    }

    const factoringPoolsBlock =
        factoringPools.length > 0
            ? `{\n${factoringPools.join('\n')}\n}`
            : '{}';

    const output = `// AUTO-GENERATED by scripts/sync-registry.ts — do not edit manually.
// Source: ${REGISTRY_URL}
// Generated at: ${new Date().toISOString()}

import type { EthAddress, ChainId } from '../domain/types/eth.js';

export interface ChainContracts {
    readonly bullaInstantPayment: EthAddress;
    readonly bullaInvoice?: EthAddress;
    readonly frendLendV2?: EthAddress;
    readonly bullaApprovalRegistry?: EthAddress;
    readonly bullaClaimV2?: EthAddress;
}

export const REGISTRY: Record<ChainId, ChainContracts> = {
${contracts.join('\n')}
};

export const SUBGRAPH_ENDPOINTS: Record<ChainId, string> = {
${subgraphs.join('\n')}
};

export const CHAIN_DISPLAY_NAMES: Record<ChainId, string> = {
${chainNames.join('\n')}
};

export interface FactoringPool {
    readonly name: string;
    readonly address: EthAddress;
}

export const FACTORING_POOLS: Partial<Record<ChainId, readonly FactoringPool[]>> = ${factoringPoolsBlock};
`;

    const outDir = resolve(projectRoot, 'src', 'generated');
    mkdirSync(outDir, { recursive: true });

    const outPath = resolve(outDir, 'registry.ts');
    writeFileSync(outPath, output, 'utf-8');
    console.log(`Generated: ${outPath}`);
}

main();
