/**
 * sync-registry.ts
 *
 * Reads registry.json from bulla-registry and generates a typed TypeScript module
 * at src/generated/registry.ts. The generated file is committed to the repo.
 *
 * Usage:
 *   yarn sync-registry
 *
 * Sources (tried in order):
 *   1. Local sibling: ../bulla-registry/registry.json (relative to repo root)
 *   2. Environment variable: BULLA_REGISTRY_PATH
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SUPPORTED_CHAIN_IDS } from '../src/domain/types/eth.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

interface RegistryNetwork {
    name: string;
    chainId: number;
    graphql: string;
    contracts: Record<string, Record<string, string>>;
}

interface Registry {
    generatedAt: string;
    networks: Record<string, RegistryNetwork>;
}

function findRegistryPath(): string {
    if (process.env.BULLA_REGISTRY_PATH) {
        return process.env.BULLA_REGISTRY_PATH;
    }

    // Try common sibling locations
    const candidates = [
        resolve(projectRoot, '..', 'bulla-registry', 'registry.json'),
        resolve(projectRoot, '..', '..', 'bulla-registry', 'registry.json'),
    ];

    for (const candidate of candidates) {
        try {
            readFileSync(candidate, 'utf-8');
            return candidate;
        } catch {
            // continue
        }
    }

    throw new Error(
        `Could not find registry.json. Tried:\n${candidates.map(c => `  - ${c}`).join('\n')}\nSet BULLA_REGISTRY_PATH to override.`,
    );
}

function main() {
    const registryPath = findRegistryPath();
    console.log(`Reading registry from: ${registryPath}`);

    const raw = readFileSync(registryPath, 'utf-8');
    const registry: Registry = JSON.parse(raw);

    const contracts: string[] = [];
    const subgraphs: string[] = [];
    const chainNames: string[] = [];

    for (const chainIdStr of Object.keys(registry.networks)) {
        const chainId = Number(chainIdStr);
        if (!(SUPPORTED_CHAIN_IDS as readonly number[]).includes(chainId)) continue;

        const network = registry.networks[chainIdStr]!;

        // Extract bullaInstantPayment address from bulla-contracts group
        const bullaContracts = network.contracts['bulla-contracts'];
        const instantPaymentAddr = bullaContracts?.['bullaInstantPayment'];

        // Extract bullaInvoice address from bulla-contracts-v2 group
        const bullaContractsV2 = network.contracts['bulla-contracts-v2'];
        const invoiceAddr = bullaContractsV2?.['bullaInvoice'];

        if (!instantPaymentAddr || !invoiceAddr) {
            console.warn(`  Warning: Missing contracts for chain ${chainId} (${network.name})`);
            continue;
        }

        contracts.push(`    ${chainId}: { bullaInstantPayment: '${instantPaymentAddr}' as EthAddress, bullaInvoice: '${invoiceAddr}' as EthAddress },`);
        subgraphs.push(`    ${chainId}: '${network.graphql}',`);
        chainNames.push(`    ${chainId}: '${network.name}',`);
    }

    const output = `// AUTO-GENERATED by scripts/sync-registry.ts — do not edit manually.
// Source: ${registryPath}
// Generated at: ${new Date().toISOString()}

import type { EthAddress, ChainId } from '../domain/types/eth.js';

export interface ChainContracts {
    readonly bullaInstantPayment: EthAddress;
    readonly bullaInvoice: EthAddress;
}

export const REGISTRY: Record<ChainId, ChainContracts> = {
${contracts.join('\n')}
};

export const SUBGRAPH_ENDPOINTS: Partial<Record<ChainId, string>> = {
${subgraphs.join('\n')}
};

export const CHAIN_DISPLAY_NAMES: Record<ChainId, string> = {
${chainNames.join('\n')}
};
`;

    const outDir = resolve(projectRoot, 'src', 'generated');
    mkdirSync(outDir, { recursive: true });

    const outPath = resolve(outDir, 'registry.ts');
    writeFileSync(outPath, output, 'utf-8');
    console.log(`Generated: ${outPath}`);
}

main();
